### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by thuanvan** [ibm-uglab/IGC-trial#11]
Is it possible to have a copy of the docker file
Can IGC trial be deployed on docker engine on linux?

**Comment by sachethegde** [comment]
Hi @thuanvan It is not officially verified/validated but can be done. 

On your mac/windows where your IGC trial is installed, `docker images` command displays the docker images. Something like this.

```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
igcibm/igc                latest              d598d9736dc7        3 months ago        10.3GB
```
Step-1: 
 Now you need to create a tar file of this image by running this command. 
`docker export --output="igc_trial_image.tar" igsDocker` (windows equivalent on a windows cmd)
This may take upto 2-4 mins. 

Step-2:
Once tar file is created, you need to transfer the tar file onto your target Linux machine where you want to run IGC Trial. Also, make sure docker is installed. 

Step-3:
Run `cat igc_trial_image.tar | docker import --change 'ENTRYPOINT ["/opt/IBM/InformationServer/bin/services.sh"]' - igcibm/igc:latest`

Step-4: 
Run `docker run -t -d -p 9443:9443 -p 50000:50000 -p 31538:31538 --hostname=igcdocker --privileged=true --name=igsDocker igcibm/igc:latest bash` on your Linux machine
Please make sure the ports are not being used by other services. 

Please let me know if you have any questions. 

You're all set to use IGC trial on this url after 2-3 mins. `https://localhost:9443/ibm/iis/igc/`

**Comment by thuanvan** [comment]
Thank you

**Comment by jose78** [comment]
Hi,

I´m playing with the IGC-Docker trial version for Windows. Two days ago the igc died, I have tried to create a container using your command 

> docker run -t -d -p 9443:9443 -p 50000:50000 -p 31538:31538 --hostname=igcdocker --privileged=true --name=igsDocker igcibm/igc:latest bash

and it is the result:

> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint igsDocker (f134b7cdf683d7c1ae677e4a682ed79334ce6ef1a9aae5 57fd69085d8322a8e5): Error starting userland proxy: Bind for 0.0.0.0:50000: unexpected error Permission denied.

This is my version of Docker:
Version:      17.03.1-ce-rc1                                                                                                                                                                               API version:  1.27                                                                                                                                                                                         Go version:   go1.7.5                                                                                                                                                                                      Git commit:   3476dbf                                                                                                                                                                                      Built:        Wed Mar 15 20:33:22 2017                                                                                                                                                                     OS/Arch:      windows/amd64                                                                                                                                                                                                                                                                                                                                                                                          Server:                                                                                                                                                                                                     Version:      17.03.1-ce-rc1                                                                                                                                                                               API version:  1.27 (minimum version 1.12)                                                                                                                                                                  Go version:   go1.7.5                                                                                                                                                                                      Git commit:   3476dbf                                                                                                                                                                                      Built:        Wed Mar 15 20:28:18 2017                                                                                                                                                                     OS/Arch:      linux/amd64                                                                                                                                                                                  Experimental: true

What is wrong? Thanks for your time. 
Regards,
JC

**Comment by sachethegde** [comment]
@jose78 
IGC Trial has ended and currently there is no direct replacement. IGC Trial offered a previous version of Information Governance Catalog and did not allow users to fully experience the current capabilities and advanced search and classification services found in version 11.7. Going forward, IBM has made the statement to combine the capabilities of Information Governance Catalog with that of Watson Knowledge Catalog to deliver a singular Data Catalog experience that benefits from the capabilities and functionality of both. Supporting a complete Governance and Quality solution, as well as ability for Self-Service and Data Science. In the interim we invite customers to trial Watson Knowledge Catalog.
