### ISSUE TITLE
Installation not allowed

### ISSUE THREAD

**Issue by KarthikVundela** [ibm-uglab/IGC-trial#12]
The prompt that I am shown with when I install try to install the trial version is as follows
Your system does not meet the pre-requisites

Your system has 7.655052185058594 GB of total memory and 4 CPUs, which does not meet the pre-requisites
System requirements are:
•	Mac OSX 10.11 and above
•	Windows 7 and 10 (64-bit)
•	4 CPU cores
•	8 GB of memory

The configuration of my machine is as follows:
Processor:Intel(R) Core(TM) i7-7600 CPU @ 2.80GHz 2.90 GHz
Installed memory (RAM): 8.00(7.65 GB usable)
System type: 64-bit Operating System, x64-based processor

Apparently it got installed on machines with similar configuration. Can someone help me and let me know what is going wrong with the installation?

**Comment by sachethegde** [comment]
@KarthikVundela From trial version 1.2.6 and onwards, we check if the available memory is more than or equal to 8GB on windows.

**Comment by KarthikVundela** [comment]
Interesting, the same trial version that I am trying to install did not show any error on another windows machine with 8 GB memory( of which 7.89 GB is usable)

**Comment by sachethegde** [comment]
@KarthikVundela 
In my previous answer, I made a general statement. Sorry about that.
Our implementation goes like this.  
```If(availableMem>=8*0.98), then "Proceed" ```

If the available memory is less than 7.84 we don't proceed. We have seen many windows machines having a problem while running IGC when available memory is low, hence this hard stop.

**Comment by KarthikVundela** [comment]
That explains everything. Thanks for the information. It will be great if the system requirement instructions are updated with a memory requirement greater than 8 GB instead of keeping it to be 8 GB. That will save time for someone like me in future before attempting to install it!

I am upgrading the RAM to 16 GB. Hopefully, the installation goes without any problems after that. I will let you know once it is done.

**Comment by sachethegde** [comment]
8 GB of total memory is still valid. To be precise We will update the doc and error message to 7.84 GB available memory.
Thank you for your input. 
Let me know how did the installation go on the upgraded machine.
