### ISSUE TITLE
com.docker.supervisor failed to start

### ISSUE THREAD

**Issue by thuanvan** [ibm-uglab/IGC-trial#13]
trying on Mac sierra and getting

com.docker.supervisor failed to start

**Comment by sachethegde** [comment]
@thuanvan It is a docker related issue. Can you please try re-installing the docker? You may also clean up com.docker files in your Library.  
This is just my suggestion. Please feel free to look up more on the web.

**Comment by thuanvan** [comment]
trying docker edge version now
