### ISSUE TITLE
Stuck at Login Screen

### ISSUE THREAD

**Issue by froghollow** [ibm-uglab/IGC-trial#14]
Installed this on existing Docker on Win10 workstation.  Appeared to work ok.  https://localhost:9443/ibm/iis/igc/ takes me to login screen.   Any hints?

**Comment by sachethegde** [comment]
@froghollow That's the expected behavior. 
username: isadmin
password: isadmin 

This is also mentioned on the 4th page of the app where you launch the IGC console.

**Comment by sachethegde** [comment]
@froghollow Were you able to log in and use IGC? Please let me know.

Thanks,
