### ISSUE TITLE
How can I download and install IGC Trial?

### ISSUE THREAD

**Issue by guirahy** [ibm-uglab/IGC-trial#15]
How can I download and install IGC Trial?

**Comment by sachethegde** [comment]
Hi @guirahy 

IGC Trial has been taken down temporarily. I update you when its back on IBM Marketplace website.

Thanks,

**Comment by sachethegde** [comment]
@guirahy 
IGC Trial has ended and currently there is no direct replacement.  IGC Trial offered a previous version of Information Governance Catalog and did not allow users to fully experience the current capabilities and advanced search and classification services found in version 11.7.   Going forward, IBM has made the statement to combine the capabilities of Information Governance Catalog with that of Watson Knowledge Catalog to deliver a singular Data Catalog experience that benefits from the capabilities and functionality of both.  Supporting  a complete Governance and Quality solution, as well as ability for Self-Service and Data Science.  In the interim we invite customers to trial Watson Knowledge Catalog.
