### ISSUE TITLE
Installation Unsuccessful

### ISSUE THREAD

**Issue by Bayonleade** [ibm-uglab/IGC-trial#7]
I am trying to install the IBM information Governance Catalog trial version and it fails after 99% of installation. Is there any other thing I need to do?

Thank you.
Bayonle
![ibm information governance catalog](https://user-images.githubusercontent.com/31103646/29417681-5692d6e6-836a-11e7-8c53-8b215258939c.PNG)

**Comment by sachethegde** [comment]
@Bayonleade 
Can you please confirm the version of the app? You can click on "About IBM IGC Trial" menu on the top right corner. 
Please let me know.

Thanks,
Sachet

**Comment by Bayonleade** [comment]
Thank you Sachet.
It is version 1.2.2

**Comment by sachethegde** [comment]
Can you please confirm when did you download this version?
As of 08/14, we have rolled out the newer version 1.2.4 on the marketplace website.

**Comment by Bayonleade** [comment]
Ok, thank you.
I will download that now.

**Comment by sachethegde** [comment]
@Bayonleade Did you get a chance to run the latest IGC Trial app? Please let us know if you are still facing the installation problem.

**Comment by Bayonleadebiyi** [comment]
Yes, I was able to run  it. Thank you.
But there are other questions I would like to ask regarding the Information Governance Catalog. Can I ask here or can I get an email address I could forward the question to?

Thank you.

**Comment by sachethegde** [comment]
@Bayonleadebiyi @Bayonleade 
Please feel free to post your questions on IGC in the forum.
https://developer.ibm.com/answers/topics/igc/

cc: @CDSLabs

**Comment by Bayonleadebiyi** [comment]
Thank you
